# Generated by Django 3.0.7 on 2020-06-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0002_trainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantime', models.TextField(max_length=50)),
                ('planamount', models.TextField(max_length=50)),
                ('classperiod', models.TextField(max_length=50)),
                ('classtype', models.TextField(max_length=50)),
                ('classequiment', models.TextField(max_length=50)),
                ('trainer', models.TextField(max_length=50)),
                ('classtime', models.TextField(max_length=50)),
            ],
        ),
    ]
