# Generated by Django 3.0.7 on 2020-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('workouttypes', models.TextField(max_length=20)),
                ('workoutmethods', models.TextField(max_length=20)),
            ],
        ),
    ]
