# Generated by Django 3.0.7 on 2020-06-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0004_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('video', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
