# Generated by Django 3.0.7 on 2020-06-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
