# Generated by Django 3.0.7 on 2020-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0006_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUTUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField(max_length=20)),
            ],
        ),
    ]
