# Generated by Django 3.0.7 on 2020-06-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0007_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='para',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
