# Generated by Django 3.0.7 on 2020-06-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0008_auto_20200612_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='video',
        ),
    ]
