# Generated by Django 3.0.7 on 2020-06-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0009_remove_aboutus_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image',
            new_name='video',
        ),
    ]
