# Generated by Django 3.0.7 on 2020-06-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0011_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('workout_name', models.TextField(max_length=10)),
                ('trainer_name', models.TextField(max_length=10)),
            ],
        ),
    ]
