# Generated by Django 3.0.7 on 2020-06-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0012_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAYS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='trainer_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='workout_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='weekdays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reebound.DAYS'),
        ),
    ]
