# Generated by Django 3.0.7 on 2020-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0015_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='monday_trainer',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mondayworkout',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
