# Generated by Django 3.0.7 on 2020-06-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0016_auto_20200614_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
