# Generated by Django 3.0.7 on 2020-06-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0018_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reebound.Trainers'),
        ),
    ]
