# Generated by Django 3.0.7 on 2020-06-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0019_timetable_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='monday_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reebound.Trainers'),
        ),
    ]
