# Generated by Django 3.0.7 on 2020-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0020_auto_20200614_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='chooseus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.TextField(max_length=20)),
                ('nutrition', models.TextField(max_length=20)),
                ('training', models.TextField(max_length=20)),
                ('needs', models.TextField(max_length=20)),
            ],
        ),
    ]
