# Generated by Django 3.0.7 on 2020-06-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0021_chooseus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooseus',
            name='equipment',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='needs',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='nutrition',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='training',
            field=models.TextField(max_length=40),
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('heading', models.TextField(max_length=50)),
                ('para', models.TextField(max_length=200)),
                ('choo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reebound.chooseus')),
            ],
        ),
    ]
