# Generated by Django 3.0.7 on 2020-06-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reebound', '0022_auto_20200615_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='choo',
        ),
        migrations.DeleteModel(
            name='chooseus',
        ),
    ]
